### ISSUE TITLE
Bug in Game class

### ISSUE THREAD

**Issue by salborrelli** [amyboyd/pgn-parser#5]
There is a clear bug in the `Game.setSite()` method. At line 105 of `Game.php` I read:

`} elseif (strlen(preg_replace('/[^a-zA-Z]/', '', $site) < 2)) {`

while the correct condition should be:

`} elseif (strlen(preg_replace('/[^a-zA-Z]/', '', $site)) < 2) {`

I would be happy to fix the problem and create a new pull request for it, but it looks like I can't create a new branch to start with, see screenshot below:

![Screenshot 2021-07-15 at 17 56 36](https://user-images.githubusercontent.com/1098233/125818965-aab4c32b-9fce-4222-b098-2b07c4a84411.png)

**Comment by amyboyd** [comment]
Wow, it has been a longggg time since I made this library! I totally forgot about it.

Thanks for finding the bug. You are right, it should have been obvious! 🤒 

I've pushed a commit with the fix -- https://github.com/amyboyd/pgn-parser/commit/557426dfbda3ec2081b1ed678d4d72ce033be04f -- and pushed a new version `0.4` to Composer/Packagist.

Thanks again for reporting this!

**Comment by salborrelli** [comment]
Thank you Amy for fixing the problem and, more in general, for your work on this library. I have recently been using the library for a small project (the web site of my Chess Club :slightly_smiling_face:

Honestly, I have been experimenting with a lot of similar libraries and I think yours is still one of the best around.
